"""empty message

Revision ID: 0ce6927d100e
Revises: 65951b0437e5
Create Date: 2023-02-02 04:06:47.744687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ce6927d100e'
down_revision = '65951b0437e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('anuncio_texto_key', type_='unique')
        batch_op.create_unique_constraint(None, ['content'])
        batch_op.drop_column('date')
        batch_op.drop_column('texto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texto', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('anuncio_texto_key', ['texto'])
        batch_op.drop_column('content')

    # ### end Alembic commands ###
