"""empty message

Revision ID: 65951b0437e5
Revises: bb87e0eb7335
Create Date: 2023-02-01 23:41:23.855602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65951b0437e5'
down_revision = 'bb87e0eb7335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anuncio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=120), nullable=False),
    sa.Column('img', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('texto'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anuncio')
    # ### end Alembic commands ###
