"""empty message

Revision ID: 86542b0d2f87
Revises: e911ed4cceed
Create Date: 2023-02-07 03:24:17.287193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86542b0d2f87'
down_revision = 'e911ed4cceed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anuncio1')
    op.drop_table('anuncio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anuncio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('profile_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='anuncio_pkey'),
    sa.UniqueConstraint('email', name='anuncio_email_key'),
    sa.UniqueConstraint('username', name='anuncio_username_key')
    )
    op.create_table('anuncio1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('img', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='anuncio1_pkey'),
    sa.UniqueConstraint('content', name='anuncio1_content_key'),
    sa.UniqueConstraint('username', name='anuncio1_username_key')
    )
    # ### end Alembic commands ###
