"""empty message

Revision ID: 937b00b867a1
Revises: 86542b0d2f87
Create Date: 2023-02-08 03:51:48.506790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937b00b867a1'
down_revision = '86542b0d2f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca', sa.String(length=280), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicacion', schema=None) as batch_op:
        batch_op.drop_column('marca')

    # ### end Alembic commands ###
