"""empty message

Revision ID: e911ed4cceed
Revises: 0ce6927d100e
Create Date: 2023-02-02 04:35:20.958985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e911ed4cceed'
down_revision = '0ce6927d100e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anuncio1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=120), nullable=False),
    sa.Column('img', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('anuncio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('profile_name', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('anuncio_content_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('img')
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('img', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('anuncio_content_key', ['content'])
        batch_op.drop_column('profile_name')
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    op.drop_table('anuncio1')
    # ### end Alembic commands ###
